namespace CreatePipe.ViewFilters
{
    //[Transaction(TransactionMode.Manual)]
    //public class Command : IExternalCommand
    //{
    //    public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
    //    {
    //        UIDocument uiDoc = commandData.Application.ActiveUIDocument;
    //        Document doc = uiDoc.Document;
    //        Autodesk.Revit.DB.View activeView = uiDoc.ActiveView;
    //        UIApplication uiApp = commandData.Application;
    //        Autodesk.Revit.ApplicationServices.Application application = uiApp.Application;

    //        ViewFiltersForm viewFiltersForm = new ViewFiltersForm(uiApp);
    //        viewFiltersForm.ShowDialog();

    //        return Result.Succeeded;
    //    }
    //}
}
